#!/bin/bash

LIMIT=98  # Upper limit

echo
echo "Printing Numbers 1 through 20 (but not 3 and 11)."

a=0

while [ $a -le "$LIMIT" ]
do
 a=$(($a+1))

 cp rooms.95 rooms.$a
 cp objs.95 objs.$a
 cp mobs.95 mobs.$a
 cp resets.95 resets.$a

 echo -n "$a "
done 

